name: pr-flow
on:
  push:
    branches: 'main'
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: organizations
    permissions:
      pull-requests: write
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -auto-approve
        env:
          WORKOS_API_KEY: ${{ secrets.WORKOS_API_KEY }}